### PR TITLE
global: rename of `pid_type` to `depid`

### LINKED ISSUE #44: global: naming consistency
Should we consider changing some of the names in the module while it's still easy:

- ``invenio-deposit`` -> ``invenio-deposits`` (plus all instances of module name usage in directory structures, config).
- ``_deposit`` -> ``_internal`` (deposit-specific stuff in JSON metadata)
- ``pid_type='dep'`` -> ``pid_type='depid'`` (*invenio_deposit/config.py*)

### PR DESCRIPTION
**Pull request by JavierDelgadoFernandez**
* Changes the default `pid_type` to `depid`. (closes #44)

* Removes unused imports.

Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@JavierDelgadoFernandez can you please check the failing tests?

**Comment by JavierDelgadoFernandez** [comment]
@jirikuncar @lnielsen With ``invenio-records-files==1.0.0a2`` all the test pass successfully. With ``1.0.0a3`` or higher, 5 tests are failing. I'm checking now how to fix it.

**Comment by jirikuncar** [comment]
- `id` has been changed to `key`

**Comment by hachreak** [comment]
I can confirm, it's failing also for me...
what exactly is changed? 
Someone is already in-charge of fix it?

**Pull request closed without merging**
