### PR TITLE
views: unused error handler removal

### PR DESCRIPTION
**Pull request by hachreak**
* Removes a no more useful error handler.
  (addresses inveniosoftware/invenio-deposit#91)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@hachreak `s/unuseful/unused/`

**Comment by hachreak** [comment]
@jirikuncar could you please release invenio-files-rest? thanks

**Comment by hachreak** [comment]
waiting for invenio-files-rest 1.0.0a4

**Comment by hachreak** [comment]
ping @jirikuncar

**Pull request merged**
