### PR TITLE
installation: pin node-semver to < 0.2.0

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by hachreak** [comment]
waiting for https://github.com/inveniosoftware/invenio-accounts/pull/248

**Comment by hachreak** [comment]
ping @nharraud

**Comment by jacquerie** [comment]
Why here and not in `invenio-assets`? If you'd put it there we could close https://github.com/inspirehep/inspire-next/issues/2750, here it would have no effect for us, as we don't use `invenio-deposit`...

**Comment by hachreak** [comment]
@jacquerie maybe you are right! :+1: 
I didn't think about it, thanks :smile:

**Comment by hachreak** [comment]
overtaken by https://github.com/inveniosoftware/invenio-assets/pull/73

**Pull request closed without merging**
