### PR TITLE
global: fix CLI and Invenio-Records-REST

### LINKED ISSUE #138: installation: bump to invenio-records-rest v1.0.0a17 (when released)
- [ ] Remove TODO and FIXME in `invenio_deposit/ext.py`.

### PR DESCRIPTION
**Pull request by jirikuncar**
- Fixes issues after updating Invenio-Records-REST to v1.0.0a17.
  (closes #138)

Signed-off-by: Jiri Kuncar jiri.kuncar@cern.ch

### CODE REVIEW

**Comment by slint** [comment]
@jirikuncar What is the status of this PR?

**Comment by jirikuncar** [comment]
LGTM

**Comment by krzysztof** [comment]
@jirikuncar The original PR as well as my commit all fail with the same error: https://travis-ci.org/inveniosoftware/invenio-deposit/jobs/172285589

**Comment by krzysztof** [comment]
Depends on https://github.com/inveniosoftware/invenio-oauth2server/pull/91

**Comment by slint** [comment]
@krzysztof Can this be merged now that inveniosoftware/invenio-oauth2server#91 is merged?

**Comment by jirikuncar** [comment]
@slint I have restarted Travis.

**Comment by slint** [comment]
https://travis-ci.org/inveniosoftware/invenio-deposit/jobs/172597135#L582 `isort` shenanigans detected.

**Comment by jirikuncar** [comment]
@slint @krzysztof is it really necessary to change the `app` to `api_app` everywhere?

**Comment by krzysztof** [comment]
@jirikuncar I don't know, do you have time to take this PR over? Sorry I don't have time to figure out why this still fails.

**Comment by hachreak** [comment]
any news about this PR? :)

**Comment by jirikuncar** [comment]
There is a problem with `Requirement.parse('kombu<3.1,>=3.0.37'))`. (a) we pin it (b) we fix invenio-* dependencies.

**Comment by jirikuncar** [comment]
It's waiting for https://github.com/inveniosoftware/invenio-files-rest/pull/135 + release.

**Comment by lnielsen** [comment]
LGTM

**Pull request merged**
