### PR TITLE
global: extra descriptions to deposit metadata

### PR DESCRIPTION
**Pull request by krzysztof**
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

### CODE REVIEW

**Comment by krzysztof** [comment]
@jirikuncar :-1: :+1: ?

**Comment by jirikuncar** [comment]
@krzysztof shall we document all fields or just two of them?

**Comment by jirikuncar** [comment]
ping @krzysztof

**Comment by krzysztof** [comment]
@jirikuncar updated with more descriptions and titles.

Any suggestions ? There's probably value in more detailed description of ``_deposit.pid.revision_id`` and it's relation to record merging.

**Comment by jirikuncar** [comment]
@krzysztof LGTM. Please rebase.

**Comment by jirikuncar** [comment]
ping @krzysztof

**Comment by krzysztof** [comment]
@jirikuncar Rebased.

**Pull request merged**
