### PR TITLE
config: usage of {} instead dict()

### PR DESCRIPTION
**Pull request by jirikuncar**
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

### CODE REVIEW

**Comment by david-caro** [comment]
I'm curious, is there any advantage of using '{}' instead of the 'dict()' form?

**Comment by jirikuncar** [comment]
@david-caro no function calls:
```
In [4]: def slow():
   ...:     return dict(foo='bar')
   ...:

In [5]: def fast():
    return {'foo': 'bar'}
   ...:

In [6]: dis.dis(slow)
  2           0 LOAD_GLOBAL              0 (dict)
              3 LOAD_CONST               1 ('foo')
              6 LOAD_CONST               2 ('bar')
              9 CALL_FUNCTION          256
             12 RETURN_VALUE

In [7]: dis.dis(fast)
  2           0 BUILD_MAP                1
              3 LOAD_CONST               1 ('bar')
              6 LOAD_CONST               2 ('foo')
              9 STORE_MAP
             10 RETURN_VALUE
```

**Comment by david-caro** [comment]
good to know, I hope I'll never have to use it though, such extreme performance tweak suggest that the code is very very sensitive to performance issues... painful :wink:

**Comment by jirikuncar** [comment]
@david-caro it's Python 😉

**Comment by david-caro** [comment]
Have you considered moving to another language?

**Pull request merged**
